main/urls.py
from django.urls import path,include
from main.views import create_product_flutter, show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id 

#Tugas 4
from main.views import register,login_user,logout_user,add_product,sell_product,remove_product

#Tugas 6
from main.views import get_product_json, add_product_ajax,del_product_ajax
app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    #Bonus Tugas 4
    path('add/', add_product, name='add_product'),
    path('remove/', sell_product, name='sell_product'),
    path('delete/', remove_product, name='remove_product'),
    #Tugas 6
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('delete-product-ajax/', del_product_ajax, name='del_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.TextField()
    amount = models.IntegerField()
    date_added = models.DateField(auto_now_add=True)

main/forms.py
from django.forms import ModelForm
from main.models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description","amount"]

main/views.py
import json
from django.http import HttpResponseRedirect, JsonResponse
from main.forms import ProductForm
from main.models import Product
from django.http import HttpResponse
from django.urls import reverse
from django.core import serializers
from django.shortcuts import render


#Tugas 4
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime

#Tugas 6
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseNotFound
from django.urls import reverse

# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    products = Product.objects.filter(user=request.user)

    context = {
        'name': request.user.username,
        'products': products,
        'stock' : products.count(),
        # 'last_login': request.COOKIES['last_login'],
    }
    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

#Tugas 4
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def add_product(request): #Bonus
    if request.method == 'POST':
        product_id = request.POST.get('product_id')
        try:
            product = Product.objects.get(id=product_id)
            product.amount += 1
            product.save()
        except Product.DoesNotExist:
            pass

    return redirect('main:show_main')

def sell_product(request): #Bonus
    if request.method == 'POST':
        product_id = request.POST.get('product_id')
        try:
            product = Product.objects.get(id=product_id)
            product.amount -= 1
            if product.amount == 0:
                product.delete()
            else:
                product.save()
        except Product.DoesNotExist:
            pass

    return redirect('main:show_main')

def remove_product(request): #Bonus
    if request.method == 'POST':
        product_id = request.POST.get('product_id')
        try:
            product = Product.objects.get(id=product_id)
            product.delete()
        except Product.DoesNotExist:
            pass

    return redirect('main:show_main')

# Tugas 6
def get_product_json(request):
    product_item = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        description = request.POST.get("description")
        price = request.POST.get("price")
        amount = request.POST.get("amount")
        user = request.user

        new_product = Product(name=name, price=price, description=description, amount = amount,user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def del_product_ajax(request):
    if request.method == 'POST':
        product_id = request.POST.get('product_id')
        try:
            product = Product.objects.get(id=product_id)
            product.delete()
        except Product.DoesNotExist:
            pass

        return HttpResponse(b"DELETED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Product.objects.create(
            user = request.user,
            name = data["name"],
            price = int(data["price"]),
            description = data["description"],
            amount = data["amount"],
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_product.html
{% extends 'base.html' %} 

{% block content %}
<h1>Insert  New Game</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}
{% block meta %}
    <title>Login</title>
{% endblock meta %}
{% block content %}

<div class="card login_card">

    <h1>GameStock</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td colspan="2" class="btn-container">
                    <input class="btn login_btn" type="submit" value="Login">
                    <a class="btn register_btn" href="{% url 'main:register' %}">Register</a>
                </td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
</div>

<style type="text/css">
    body {
        background-image: url("https://images.unsplash.com/photo-1696351383130-f3c9ed9e1bf0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2532&q=80");
        background-size: cover; 
        background-position: center; 
        background-repeat : no-repeat;
        height: 100vh;
        margin: 0;
        display: flex;
        justify-content: center;
        align-items: center;
    }
        
    .card.login_card {
        max-width: 300px;
        min-height: 200px;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        padding: 35px;
        border: 1px solid rgba(255, 255, 255, .25);
        border-radius: 20px;
        background-color: rgba(255, 255, 255, 0.45);
        box-shadow: 0 0 10px 1px rgba(0, 0, 0, 0.25);
        backdrop-filter: blur(10px);
        text-align: center; /* Center text within the card */
        margin: auto; /* Center the card on the page */
    }

    .card.login_card h1 {
        font-family: 'Pixelify Sans', cursive;
    }

    .btn-container {
        text-align: center; /* Center buttons within the container */
    }

    .btn {
        margin: 5px; /* Add some space between buttons */
        transition: background-color 0.3s, padding 0.3s; 
        background-color: transparent;
        border: none;
        outline: none;
        color: green;
    }
    .btn:hover {
        background-color: green; /* Change to blue on hover */
        color: whitesmoke;
         /* Increase padding on hover */
    }
</style>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
    <div class="modal fade" id="addModal" tabindex="-1" aria-labelledby="addModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="addModalLabel">Add New Product</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" class="form-control" id="name" name="name"></input>
                        </div>
                        <div class="mb-3">
                            <label for="price" class="col-form-label">Price</label>
                            <input type="number" class="form-control" id="price" name="price"></input>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="col-form-label">Description:</label>
                            <textarea class="form-control" id="description" name="description"></textarea>
                        </div>
                            <div class="mb-3">
                            <label for="amount" class="col-form-label">Amount:</label>
                            <input type="number" class="form-control" id="amount" name="amount"></input>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
                </div>
            </div>
        </div>
    </div>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand">GameStock</a>
        <a class="navbar-brand">{{name}}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only"></span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href=""  data-bs-toggle="modal" data-bs-target="#addModal">Add Game</a>
              </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:logout' %}">Logout</a>
            </li>
          </ul>
        </div>
      </nav>
    

    <h5>Sesi terakhir login: {{ last_login }}</h5>

    <h5 id="currentStock">Current Game Stock: {{stock}}</h5> <!-- Bonus Poin -->

    <div class="row" id = "ItemCard"></div>
    
    
    <style>
        .product-card {
            max-width: 300px;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 10px;
            margin-bottom: 10px;
            background-color: #f9f9f9;
        }
        
        .product-card form {
            display: inline-block;
        }

        .last-product { 
            background-color: grey;
        }
    </style>

    <script>
        async function getProducts() {
            return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
        }
        async function refreshProducts() {
        document.getElementById("ItemCard").innerHTML = ""
            const products = await getProducts()
            let htmlString = ``
            let totalAmount = 0;
            products.forEach((item,index) => {
                htmlString += 
                `\n<div class="col-md-4">
                <div class="card product-card ${index === products.length - 1 ? 'last-product' : ''}"> <!-- Bonus Poin -->
                    <h3>${item.fields.name}</h3>
                    <p>Price: ${item.fields.price}</p>
                    <p>Description: ${item.fields.description}</p>
                    <p>Amount: ${item.fields.amount}</p>
                    <p>Date Added: ${item.fields.date_added}</p>
                    
                    <form action="{% url 'main:add_product' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="product_id" value="${item.pk}">
                        <button type="submit" class="btn btn-success">+</button>
                    </form>
                    <form action="{% url 'main:sell_product' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="product_id" value="${item.pk}">
                        <button type="submit" class="btn btn-warning">-</button>
                    </form>
                        <input type="button" id= "del_button" class="btn btn-danger" value="Delete" onclick ="delProduct(${item.pk})">
                </div>
            </div>` 
            totalAmount += item.fields.amount
            })
            
            document.getElementById("ItemCard").innerHTML = htmlString
            document.getElementById("currentStock").innerText = `Current Game Stock: ${totalAmount}`;
        }
        refreshProducts()

        function addProduct() {
            fetch("{% url 'main:add_product_ajax' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(refreshProducts)

            document.getElementById("form").reset()
            return false
        }
        document.getElementById("button_add").onclick = addProduct
    
        function delProduct(key) {
            const formData = new FormData();
            formData.append('product_id', key);
            fetch("{% url 'main:del_product_ajax' %}", {
                method: "POST",
                body: formData
            }).then(refreshProducts)
            
            document.getElementById("form").reset()
            return false
        }
    </script>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  

<div class="container">
    <div class="card register-card">
        <h1>Register</h1>

        <form method="POST" class="input-container">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
                <tr>
                    <td></td>
                    <td colspan="2" class="btn-container">
                        <button type="submit" class="btn btn-primary">Daftar</button>
                        <a href="{% url 'main:login' %}" class="btn btn-primary">Kembali</a>
                    </td>
                </tr>
            </table>
        </form>

        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
</div>

<style type="text/css">
    body {
        background-image: url("https://images.unsplash.com/photo-1696351383130-f3c9ed9e1bf0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2532&q=80");
        background-size: cover; 
        background-position: center; 
        background-repeat : no-repeat;
        height: 100vh;
        margin: 0;
        display: flex;
        justify-content: flex-start; /* Move content to the left */
        align-items: center;
    }
    
    .card.register-card {
        max-width: 600px;
        min-height: 200px;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        padding: 35px;
        border: 1px solid rgba(255, 255, 255, .25);
        border-radius: 20px;
        background-color: rgba(255, 255, 255, 0.45);
        box-shadow: 0 0 10px 1px rgba(0, 0, 0, 0.25);
        backdrop-filter: blur(10px);
        text-align: center;
        margin: auto; /* Center the card vertically */
    }

    .helptext{
        display: none;
    }
    .card.register-card h1 {
        font-family: 'Pixelify Sans', cursive;
    }

    .btn-container {
    text-align: center;
    display: flex;
    justify-content: center; /* Center the buttons horizontally */
}

.btn {
    margin: 5px;
    transition: background-color 0.3s, padding 0.3s;
    background-color: transparent;
    border: none;
    outline: none;
    color: green;
}
.btn:hover {
    background-color: green;
    color: whitesmoke;
}   

</style>

{% endblock content %}